spring:
  profiles:
    active: dev
  application:
    name: microservice-a
  mvc:
    servlet:
      path: /microservice-a
  jpa:
    tdengine:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    druid:
      tdengine:
        driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
        url: jdbc:TAOS-RS://47.75.196.191:6041/db?user=dev&password=tddevP@ssw0RD
        username: dev
        password: tddevP@ssw0RD

logging:
  level:
    cn.helloworld.microservicea.service.feign: debug


